--- Dockerfile.orig	2018-12-06 18:51:40.787441506 +0900
+++ Dockerfile	2018-12-06 18:51:32.043648457 +0900
@@ -4,24 +4,13 @@
 USER root
 
 ###
+### Modified based on:
 ### https://gitlab.com/nvidia/cuda/raw/centos6/10.0/base/Dockerfile
 ###
 
-RUN NVIDIA_GPGKEY_SUM=d1be581509378368edeec8c1eb2958702feedf3bc3d17011adbf24efacce4ab5 && \
-    curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/rhel6/x86_64/7fa2af80.pub | sed '/^Version/d' > /etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA && \
-    echo "$NVIDIA_GPGKEY_SUM  /etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA" | sha256sum -c -
-
-COPY cuda.repo /etc/yum.repos.d/cuda.repo
-
 ENV CUDA_VERSION 10.0.130
 
 ENV CUDA_PKG_VERSION 10-0-$CUDA_VERSION-1
-# For libraries in the cuda-compat-* package: https://docs.nvidia.com/cuda/eula/index.html#attachment-a
-RUN yum install -y \
-        cuda-cudart-$CUDA_PKG_VERSION \
-        cuda-compat-10-0-410.48 && \
-    ln -s cuda-10.0 /usr/local/cuda && \
-    rm -rf /var/cache/yum/*
 
 ENV PATH /usr/local/cuda/bin:${PATH}
 
@@ -31,24 +20,16 @@
 ENV NVIDIA_REQUIRE_CUDA "cuda>=10.0 brand=tesla,driver>=384,driver<385"
 
 ###
-### https://gitlab.com/nvidia/cuda/raw/centos6/10.0/runtime/Dockerfile
-###
-
-RUN yum install -y \
-        cuda-libraries-$CUDA_PKG_VERSION \
-        cuda-nvtx-$CUDA_PKG_VERSION && \
-    rm -rf /var/cache/yum/*
-
-###
-### https://gitlab.com/nvidia/cuda/raw/centos6/10.0/devel/Dockerfile
+### Run `runfile` installer
 ###
 
-RUN yum install -y \
-        cuda-libraries-dev-$CUDA_PKG_VERSION \
-        cuda-nvml-dev-$CUDA_PKG_VERSION \
-        cuda-minimal-build-$CUDA_PKG_VERSION \
-        cuda-command-line-tools-$CUDA_PKG_VERSION && \
-    rm -rf /var/cache/yum/*
+RUN CUDA_DRIVER_VERSION=410.48 && \
+    CUDA_RUNFILE_INSTALLER=/tmp/installer.run && \
+    curl -o "${CUDA_RUNFILE_INSTALLER}" -L "https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_${CUDA_VERSION}_${CUDA_DRIVER_VERSION}_linux" && \
+    sh "${CUDA_RUNFILE_INSTALLER}" --silent --toolkit && \
+    rm "${CUDA_RUNFILE_INSTALLER}" && \
+    echo "/usr/local/cuda/lib64" > /etc/ld.so.conf.d/cuda.conf && \
+    ldconfig
 
 ENV LIBRARY_PATH /usr/local/cuda/lib64/stubs
 
