--- generated/Dockerfile	2018-12-06 19:38:49.959543857 +0900
+++ Dockerfile	2018-12-06 19:37:34.057237324 +0900
@@ -4,6 +4,7 @@
 USER root
 
 ###
+### Modified based on:
 ### https://gitlab.com/nvidia/cuda/raw/centos6/7.5/runtime/Dockerfile
 ###
 
@@ -13,9 +14,9 @@
 
 COPY cuda.repo /etc/yum.repos.d/cuda.repo
 
-ENV CUDA_VERSION 7.5.18
+ENV CUDA_VERSION 7.0.28
 
-ENV CUDA_PKG_VERSION 7-5-7.5-18
+ENV CUDA_PKG_VERSION 7-0-7.0-28
 RUN yum install -y \
         cuda-nvrtc-$CUDA_PKG_VERSION \
         cuda-cusolver-$CUDA_PKG_VERSION \
@@ -25,7 +26,7 @@
         cuda-cusparse-$CUDA_PKG_VERSION \
         cuda-npp-$CUDA_PKG_VERSION \
         cuda-cudart-$CUDA_PKG_VERSION && \
-    ln -s cuda-7.5 /usr/local/cuda && \
+    ln -s cuda-7.0 /usr/local/cuda && \
     rm -rf /var/cache/yum/*
 
 RUN echo "/usr/local/cuda/lib64" >> /etc/ld.so.conf.d/cuda.conf && \
@@ -44,9 +45,10 @@
 # nvidia-container-runtime
 ENV NVIDIA_VISIBLE_DEVICES all
 ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
-ENV NVIDIA_REQUIRE_CUDA "cuda>=7.5"
+ENV NVIDIA_REQUIRE_CUDA "cuda>=7.0"
 
 ###
+### Modified based on:
 ### https://gitlab.com/nvidia/cuda/raw/centos6/7.5/devel/Dockerfile
 ###
 
@@ -78,16 +80,17 @@
 ENV LIBRARY_PATH /usr/local/cuda/lib64/stubs
 
 ###
+### Modified based on:
 ### https://gitlab.com/nvidia/cuda/raw/centos6/7.5/devel/cudnn5/Dockerfile
 ###
 
-ENV CUDNN_VERSION 5.1.10
+ENV CUDNN_VERSION 4.0.8
 LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"
 
 # cuDNN license: https://developer.nvidia.com/cudnn/license_agreement
-RUN CUDNN_DOWNLOAD_SUM=69ca71f7728b54b6e003393083f419b24774fecd3b08bbf41bceac9a9fe16345 && \
-    curl -fsSL http://developer.download.nvidia.com/compute/redist/cudnn/v5.1/cudnn-7.5-linux-x64-v5.1.tgz -O && \
-    echo "$CUDNN_DOWNLOAD_SUM  cudnn-7.5-linux-x64-v5.1.tgz" | sha256sum -c - && \
-    tar --no-same-owner -xzf cudnn-7.5-linux-x64-v5.1.tgz -C /usr/local && \
-    rm cudnn-7.5-linux-x64-v5.1.tgz && \
-    ldconfig
\ No newline at end of file
+RUN CUDNN_DOWNLOAD_SUM=cd091763d5889f0efff1fbda83bade191f530743a212c6b0ecc2a64d64d94405 && \
+    curl -fsSL http://developer.download.nvidia.com/compute/redist/cudnn/v4/cudnn-7.0-linux-x64-v4.0-prod.tgz -O && \
+    echo "$CUDNN_DOWNLOAD_SUM  cudnn-7.0-linux-x64-v4.0-prod.tgz" | sha256sum -c - && \
+    tar --no-same-owner -xzf cudnn-7.0-linux-x64-v4.0-prod.tgz -C /usr/local && \
+    rm cudnn-7.0-linux-x64-v4.0-prod.tgz && \
+    ldconfig
